Syrus_Web2_ThreePeat-main/ThreePeatFinal/ThreePeatMaps/did_django_google_maps_api/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('main.urls', namespace="main")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Syrus_Web2_ThreePeat-main/ThreePeatFinal/ThreePeatMaps/main/urls.py
from django.urls import path, include
from . import views


app_name = "main"

urlpatterns = [
	
		path('home/', views.home, name="home"),
		path('', views.home, name="home"),
		# path('/', views.route, name="home"),
		path('route/', views.route, name="route"),
		path('map/', views.map, name="map"),
		path('contact/', views.contact, name="contact"),
	# path('', views.route, name="home"),

	# path('', include('main.urls')),

	]

Syrus_Web2_ThreePeat-main/ThreePeatFinal/ThreePeatMaps/main/models.py
from django.db import models
from django.contrib.auth.models import User


class PastDetail(models.Model):
    updated = models.DateTimeField(auto_now=True)
    start_address =models.CharField(max_length=256,default='')
    end_address=  models.CharField(max_length=256,default='')

Syrus_Web2_ThreePeat-main/ThreePeatFinal/ThreePeatMaps/main/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, SetPasswordForm, PasswordResetForm
from django.contrib.auth.models import User
from django import forms
from .models import PastDetail


class PastForm(forms.ModelForm):
	
	start_address = forms.CharField(max_length=120, required=True, widget = forms.HiddenInput())
	end_address = forms.CharField(max_length=130, required=True, widget = forms.HiddenInput())

	class Meta:
		model = PastDetail
		fields = ('start_address','end_address')

Syrus_Web2_ThreePeat-main/ThreePeatFinal/ThreePeatMaps/main/views.py
from django.shortcuts import render
from django.conf import settings

from .mixins import Directions
'''
Basic view for routing 


'''

def home(request):
	return render(request, 'main/home.html')

def contact(request):
	return render(request, 'main/contact.html')

def route(request):

	context = {"google_api_key": settings.GOOGLE_API_KEY}
	return render(request, 'main/route.html', context)


'''
Basic view for displaying a map 
'''
def map(request):

	lat_a = request.GET.get("lat_a")
	long_a = request.GET.get("long_a")
	lat_b = request.GET.get("lat_b")
	long_b = request.GET.get("long_b")
	directions = Directions(
		lat_a= lat_a,
		long_a=long_a,
		lat_b = lat_b,
		long_b=long_b
		)

	context = {
	"google_api_key": settings.GOOGLE_API_KEY,
	"lat_a": lat_a,
	"long_a": long_a,
	"lat_b": lat_b,
	"long_b": long_b,
	"origin": f'{lat_a}, {long_a}',
	"destination": f'{lat_b}, {long_b}',
	"directions": directions,

	}
	return render(request, 'main/map.html', context)

Syrus_Web2_ThreePeat-main/ThreePeatFinal/ThreePeatMaps/main/templates/main/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- visit https://fonts.google.com/specimen/Courier+Prime?preview.text_type=custom to get script-->
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Courier+Prime&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'main.css' %}"></link>
  <!-- css bootstrap -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

  
  {% block extend_head %}

  {% endblock %}

</head>
<body>

  <!-- This allows us to extend the nav bar in HTML docs that have special requirements-->
  {% block extend_nav %}

  {% endblock %}

  <div class="div-container">
    
    {% include 'main/partials/logo.html' %}

    {% block content %}

    {% endblock %}

  </div>
<!-- js bootstrap -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  <!--visit https://code.jquery.com/ for jquery script-->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

  <!-- This allows us to extend the foot scripts in HTML docs that have special requirements-->
  {% block extend_footer %}

  {% endblock %}

  <script src="{% static 'main.js' %}"></script>
  

</body>
</html>

Syrus_Web2_ThreePeat-main/ThreePeatFinal/ThreePeatMaps/main/templates/main/contact.html
{% extends 'main/base.html' %}
{% load static %}


{% block extend_head %}

<script src='https://www.google.com/recaptcha/api.js?render={{recaptcha_site_key}}'></script>


{% endblock %}

{% block extend_nav %} 
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
    <!-- <div class="container"> -->
      <a class="navbar-brand" href="{% url 'main:home' %}">
        <!-- <img src="https://placeholder.pics/svg/150x50/888888/EEE/Logo" alt="..." height="36"> -->
        <img class="logo" src="{% static 'branding/logo new.png' %}" />
      </a>
   
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a class="nav-link " aria-current="page"  href="{% url 'main:home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="route/">Search</a>
            <!-- <li><a href="{% url 'main:route' %}">Search</a></li> -->
            <!-- <li><a class="active" href="#map">Map</a></li> -->
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Sign-Up</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="contact/">Contact us</a>
          </li>
          <li><a class="dropdown-item" href="#">Something </a></li>
          
              
            </ul>
          </li>
        </ul>
      <!-- </div> -->
    </div>
  </nav>

<section class="text-gray-200 body-font relative">
    <div class=" contact_img absolute inset-0 bg-gray-300">
      <iframe width="100%" height="100%" frameborder="0" marginheight="0" marginwidth="0" title="map" scrolling="no" src="{% static 'branding/india.jpg' %}"  style="filter: grayscale(1) contrast(1.2) opacity(0.4);"></iframe>
    </div>
    <div class="container px-5 py-24 mx-auto flex">
      <div class="lg:w-1/3 md:w-1/2 bg-white rounded-lg p-8 flex flex-col md:ml-auto w-full mt-10 md:mt-0 relative z-10 shadow-md">
        <h2 class="text-gray-900 text-lg mb-1 font-medium title-font">Contact Us</h2>
        <br>
        <div class="relative mb-4">
          <label for="email" class="leading-7 text-sm text-gray-600">Email</label>
          <input type="email" id="email" name="email" class="w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
        </div>
        <div class="relative mb-4">
          <label for="message" class="leading-7 text-sm text-gray-600">Message</label>
          <textarea id="message" name="message" class="w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 h-32 text-base outline-none text-gray-700 py-1 px-3 resize-none leading-6 transition-colors duration-200 ease-in-out"></textarea>
        </div>
        <button class="text-black bg-blue-500 border-0 py-2 px-8 focus:outline-none hover:bg-blue-600 rounded text-lg">Send</button>
        
        
      </div>
      
    </div>
   
  </section>
  

{% endblock %}


{% block content %}
{% endblock %}

Syrus_Web2_ThreePeat-main/ThreePeatFinal/ThreePeatMaps/main/templates/main/home.html
{% extends 'main/base.html' %}
{% load static %}


{% block extend_head %}

<script src='https://www.google.com/recaptcha/api.js?render={{recaptcha_site_key}}'></script>


{% endblock %}

{% block extend_nav %} 

<!-- <ul class="sidenav">
  <div class="brand-logo" >
		<img class="logo" src="{% static 'branding/yaan.png' %}" />
		
	</div>
  <li><a class="active" href="{% url 'main:route' %}">Search</a></li>
  <li><a href="javascript:void(0)" onclick="alert('Please add a start and end address')">Map</a></li>
</ul> -->
<!-- <img src={career_main} alt="FCC Logo" width={"100%"} height="550" class="acc1" ></img> -->


<!-- <nav class="navbar navbar-expand-lg bg-body-tertiary">
 
  <div class="container-fluid">
    
    <div class="brand-logo" >
      <img class="logo" src="{% static 'branding/yaan.png' %}" />
      
    </div>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="nav justify-content-end">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Active</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

<div>
  <img class="hero" src="{% static 'branding/hero-bg.jpg' %}" />
</div>   -->

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
  <!-- <div class="container"> -->
    <a class="navbar-brand" href="{% url 'main:home' %}">
      <!-- <img src="https://placeholder.pics/svg/150x50/888888/EEE/Logo" alt="..." height="36"> -->
      <img class="logo" src="{% static 'branding/logo new.png' %}" />
    </a>
 
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page"  href="{% url 'main:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="route/">Search</a>
          <!-- <li><a href="{% url 'main:route' %}">Search</a></li> -->
          <!-- <li><a class="active" href="#map">Map</a></li> -->
        </li>
        <li class="nav-item">
          <a class="nav-link" href="http://127.0.0.1:8002">Sign-Up</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="contact/">Contact us</a>
        </li>
        <li><a class="dropdown-item" href="#">Something </a></li>
        
            
          </ul>
        </li>
      </ul>
    <!-- </div> -->
  </div>
</nav>


<!-- Page Content -->
<div class="container-hero"> 
  <!-- <img class="hero" src="{% static 'branding/hero-bg.jpg' %}"style="width:100%;"> -->
  <div class="centered">
    <button type="button" class="btn bg-warning-subtle ">
      <h3>Welcome to Smart Transport System</h3>
      </button>
      <h1>Find Your YAAN Around!!!!</h1>
      
      <button type="button" class="btn btn-outline-light">Get Started</button>
      <!-- /* Define the typewriter animation */ -->
      
    
    <h1></h1>
  </div>
</div>






{% endblock %}


{% block content %}







<!-- 


{% endblock %}

{% block extend_footer %}


<script type="text/javascript">

    var google_api_key = "{{google_api_key|safe}}";

  </script>

  <script src="{% static 'google_places.js' %}"></script>


{% endblock %}

Syrus_Web2_ThreePeat-main/ThreePeatFinal/ThreePeatMaps/main/templates/main/map.html
{% extends 'main/base.html' %}
{% load static %}


{% block extend_head %}

<script src='https://www.google.com/recaptcha/api.js?render={{recaptcha_site_key}}'></script>



{% endblock %}

{% block extend_nav %} 

<ul class="sidenav">
  <div class="brand-logo" >
		<a class="navbar-brand" href="{% url 'main:home' %}">
      <!-- <img src="https://placeholder.pics/svg/150x50/888888/EEE/Logo" alt="..." height="36"> -->
      <img class="logo" src="{% static 'branding/logo new.png' %}" />
    </a>
	</div>
  <li><a href="{% url 'main:route' %}">Search</a></li>
  <li><a class="active" href="#map">Map</a></li>
</ul>

<!-- <ul class="sidenav">
  <div class="brand-logo" >
		<img class="logo" src="{% static 'branding/yaan.png' %}" />
		
	</div>
  <li><a class="active" href="{% url 'main:route' %}">Routing</a></li>
  <li><a href="javascript:void(0)" onclick="alert('Please add a start and end address')">Map</a></li>
</ul> -->

{% endblock %}


{% block content %}

<h3 id="map">RESULT</h3>

<div class="container">

  <table>
    <thead>
      <tr>
        <th>Field</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Start</td>
        <td>{{directions.origin}}</td>      
      </tr>
      <tr>
        <td>Destination</td>
        <td>{{directions.destination}}</td>      
      </tr>
      <tr>
        <td>Duration</td>
        <td>{{directions.duration}}</td>      
      </tr>
      <tr>
        <td>Distance</td>
        <td>{{directions.distance}}</td>      
      </tr>
      <tr>
        <td>Directions</td>
        <td id="dir-toggle">click <a href="javascript:void(0)" onclick="DirectionsToggle()">here</a></td>      
      </tr>

    </tbody>
  </table>

  <table id="dir-table" hidden>
    <thead>
      <tr>
        <th>Directions</th>
        <th>Distance</th>
        <th>Duration</th>
      </tr>
    </thead>
    <tbody>
      {% for dist, dur, text in directions.steps %}
      <tr>
        <td>{{text|safe}}</td>
        <td>{{dist}}</td>
        <td>{{dur}}</td>   
      </tr>
      {% endfor %}
    </tbody>
  </table>

</div>

<div class="map-container">

   <div id="map-route"></div>


</div>

{% endblock %}

{% block extend_footer %}


<script type="text/javascript">

    var google_api_key = "{{google_api_key|safe}}";
    var lat_a = {{lat_a|safe}};
    var long_a = {{long_a|safe}};
    var lat_b = {{lat_a|safe}};
    var long_b = {{long_b|safe}};
    var origin = "{{origin|safe}}";
    var destination = "{{destination|safe}}";
    var directions = {{directions|safe}}

  </script>

  <script src="{% static 'google_maps.js' %}"></script>


{% endblock %}

Syrus_Web2_ThreePeat-main/ThreePeatFinal/ThreePeatMaps/main/templates/main/partials/logo.html
{% load static %}
<a href="{% url 'main:route' %}">
	<!-- <div class="brand-logo">
		<img class="logo" src="{% static 'branding/did_logo.gif' %}" />
	</div> -->
</a>

Syrus_Web2_ThreePeat-main/ThreePeatFinal/ThreePeatMaps/main/templates/main/route.html
{% extends 'main/base.html' %}
{% load static %}


{% block extend_head %}

<script src='https://www.google.com/recaptcha/api.js?render={{recaptcha_site_key}}'></script>


{% endblock %}

{% block extend_nav %} 

<ul class="sidenav">
  <div class="brand-logo" >
		<a class="navbar-brand" href="{% url 'main:home' %}">
      <!-- <img src="https://placeholder.pics/svg/150x50/888888/EEE/Logo" alt="..." height="36"> -->
      <img class="logo" src="{% static 'branding/logo new.png' %}" />
    </a>
		
	</div>
  <li><a class="active" href="{% url 'main:route' %}">Search</a></li>
  <li><a href="javascript:void(0)" onclick="alert('Please add a start and end address')">Map</a></li>
</ul>


<!-- <ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link active" aria-current="page" href="#">Home</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Routing</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Map</a>
  </li>
  </ul> -->

{% endblock %}


{% block content %}




<h1>Welcome <i>User</i> !</h1>
<!-- <h4>Enter </h4> -->

<div class="container-route ">

   <label for="id-google-address-a">Start Address</label>
   <input type="text" placeholder="*Begin typing address" id="id-google-address-a" name="google_address_a">

   <label for="id-google-address-b">Destination Address</label>
   <input type="text" placeholder="*Begin typing address" id="id-google-address-b" name="google_address_b">


   <input type="hidden" class="geo" id="id-lat-a" value="">
   <input type="hidden" class="geo" id="id-long-a" value="">
   <input type="hidden" class="geo" id="id-lat-b" value="">
   <input type="hidden" class="geo" id="id-long-b" value="">


</div>


<!-- <button type="button" class="btn btn-warning">SEARCH</button> -->

{% endblock %}

{% block extend_footer %}



<script type="text/javascript">

    var google_api_key = "{{google_api_key|safe}}";

  </script>

  <script src="{% static 'google_places.js' %}"></script>


{% endblock %}